openapi: 3.0.0
info:
  description: |
    API specification of the publically available [TheMealDB API](https://www.themealdb.com/api.php).
  version: "1.0.0"
  title: TheMealDB API
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Tajtesz/TheMealDB/1.0.0
  - url: 'https://themealdb.swagger.io/v2'
tags:
  - name: random
    description: All the details about random meals
    externalDocs:
      description: Find out more
      url: 'https://www.themealdb.com/api.php'
paths:
  /api/json/v1/1/random.php:
    get:
      tags:
        - random
      summary: Get all the details about a random meal
      operationId: getRandomMeal
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Meal'
components:
  schemas:
    Meal:
      type: object
      properties:
        idMeal:
          type: integer
          format: int64
        strMeal:
          type: string
        strDrinkAlternate:
          type: string
        shipDate:
          type: string
          format: date-time
        strCategory:
          type: string
          description: Meal category
          enum:
            - Beef
            - Chicken
            - Dessert
            - Lamb
            - Miscellaneous
            - Pasta
            - Pork
            - Seafood
            - Side
            - Starter
            - Vegan
            - Vegetarian
            - Breakfast
            - Goat
        strArea:
          type: string
        strInstructions:
          type: string
        strMealThumb:
          type: string
        strTags:
          type: string
        strYoutube:
          type: string
        strIngredient1:
          type: string
        strIngredient2:
          type: string
        strIngredient3:
          type: string
        strIngredient4:
          type: string
        strIngredient5:
          type: string
        strIngredient6:
          type: string
        strIngredient7:
          type: string
        strIngredient8:
          type: string
        strIngredient9:
          type: string
        strIngredient10:
          type: string
        strIngredient11:
          type: string
        strIngredient12:
          type: string
        strIngredient13:
          type: string
        strIngredient14:
          type: string
        strIngredient15:
          type: string
        strIngredient16:
          type: string
        strIngredient17:
          type: string
        strIngredient18:
          type: string
        strIngredient19:
          type: string
        strIngredient20:
          type: string
        strMeasure1:
          type: string
        strMeasure2:
          type: string
        strMeasure3:
          type: string
        strMeasure4:
          type: string
        strMeasure5:
          type: string
        strMeasure6:
          type: string
        strMeasure7:
          type: string
        strMeasure8:
          type: string
        strMeasure9:
          type: string
        strMeasure10:
          type: string
        strMeasure11:
          type: string
        strMeasure12:
          type: string
        strMeasure13:
          type: string
        strMeasure14:
          type: string
        strMeasure15:
          type: string
        strMeasure16:
          type: string
        strMeasure17:
          type: string
        strMeasure18:
          type: string
        strMeasure19:
          type: string
        strMeasure20:
          type: string
        strSource:
          type: string
        dateModified:
          type: string
          format: date